#集群模式启动Eureka Server
spring: 
  application:
    name: daojia-EurekaServer
server:
  port: 6001 #启动端口
eureka: #向另一个Eureka Server注册自己为一个Client
  hostname: localhost #指定本机器的主机名
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port:6001}/daojiaeureka/eureka/ #去主机名未hadoopMaster的Eureka服务器，将自己注册为一个客户端
    
zuul:
  prefix: /test #为zuul设置一个公共的前缀
  #ignoredServices: '*'
  routes:
    cloud-client: #随便定义，当不存在serviceId时，默认该值为serviceId（就是注册服务的名称，属性spring.application.name）
      path: /baomu/** #匹配/techouse/usersystem/** 均路由到cloud-client
      serviceId: spring-cloud-producer #指定路由到的serviceId
ribbon:
  eureka:
    enabled: false #配置zuul路由时用将此属性设置为false

cloud-client:
  ribbon:
    listOfServers: localhost:9000,localhost:9001 #为cloud-client服务指定一组服务地址，应该是用于负载均衡